name: Unit testing with pytest

on:
  push:
    branches:
      - main # or the branch you want this action to be triggered on
         

jobs: # what should we do when it is run
  build:
    runs-on: ubuntu-latest # platform it runs on
    steps:
    - uses: actions/checkout@v2 # checkout your code
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # specify python version
    - name: Install dependencies # which libraries do we need for testing
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # they should be listed in this file
    - name: List directory contents  # Debugging step to see contents
      run: ls -al
    - name: Test with pytest
      run: python multiplication_mat.py
